server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cwb927/aispringcloud.git
          searchPaths: config
          username: cwb927
          password: Wyzitld0
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/